services:

  ollama-intel-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/dbirks/ollama-intel-gpu:latest
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ollama-intel-gpu:/root/.ollama
    environment:
      - DISPLAY=${DISPLAY}
    ports:
      - 11434:11434

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:v0.3.10
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama-intel-gpu
    ports:
      - ${OLLAMA_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama-intel-gpu:11434
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama-webui: {}
  ollama-intel-gpu: {}
